spring:
  application:
    name: course-platform

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  elasticsearch:
    uris: ${SECURITY_JWT_ELASTICSEARCH_URIS}
    username: ${SECURITY_JWT_ELASTICSEARCH_USERNAME}
    password: ${SECURITY_JWT_ELASTICSEARCH_PASSWORD}

security-jwt:
  private-key: ${SECURITY_JWT_PRIVATE_KEY}
  public-key: ${SECURITY_JWT_PUBLIC_KEY}
  ttl: ${SECURITY_JWT_TTL}

springdoc:
  api-docs:
    path: ${SPRINGDOC_API_DOCS_PATH}
  swagger-ui:
    path: ${SPRINGDOC_API_DOCS_SWAGGER_UI}

server:
  port: ${PORT:8080}